### ISSUE TITLE
Cannot compile ervything.c

### ISSUE THREAD

**Issue by mathewgrabau** [evrythng/evrythng-c-library#1]
I am receiving an error about a missing include when trying to compile evrythng.c into my project.

Specifically, the file is MQTTClientPersistence.h.

**Comment by rfilipenka** [comment]
Hi, Matthew, 
sorry, this file is obsolete and left by a mistake. I'll remove it shortly.
As you may have noticed this repo is aimed to be included in our sdk's and does not contain it's own build system:
https://github.com/evrythng/evrythng-marvell-sdk
https://github.com/evrythng/evrythng-broadcom-sdk
https://github.com/evrythng/evrythng-freertos-sdk

What objective do you have? What platform are you building it for? 
Feel free to contact me in case you have any questions.

**Comment by mathewgrabau** [comment]
Hi,

Thank you for clarifying that - I was aiming to use the FreeRTOS one.

Mathew
